spring:
  datasource:
    tomcat:
      remove-abandoned-timeout: 60
      remove-abandoned: true

    url: jdbc:mysql://localhost:3306/jwt-test-db
    username: ${USERNAME}
    password: ${PASSWORD}


  jpa:
    hibernate:
      use-new-id-generator-mappings: false
      ddl-auto: update

    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        format_sql: true
    generate-ddl: true



